// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIR7ZWVnNKrsZqbXl5dWRv02JBOnShZNE',
    appId: '1:254948261940:web:3f9975f4bfc234216c8a61',
    messagingSenderId: '254948261940',
    projectId: 'womensafety-58f57',
    authDomain: 'womensafety-58f57.firebaseapp.com',
    databaseURL: 'https://womensafety-58f57-default-rtdb.firebaseio.com',
    storageBucket: 'womensafety-58f57.firebasestorage.app',
    measurementId: 'G-J0EW9FS3VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqy9lKhCK_wx64NCjbQG7lyq3SKzoKXSs',
    appId: '1:416377232774:android:e2143b3961b500d343a007',
    messagingSenderId: '416377232774',
    projectId: 'busticket-1edeb',
    databaseURL: 'https://busticket-1edeb-default-rtdb.firebaseio.com',
    storageBucket: 'busticket-1edeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6E7-sLf2rjuLAeDGDAvue3QJkZYJN1qA',
    appId: '1:416377232774:ios:dc8b0f1a3b8e0b8843a007',
    messagingSenderId: '416377232774',
    projectId: 'busticket-1edeb',
    databaseURL: 'https://busticket-1edeb-default-rtdb.firebaseio.com',
    storageBucket: 'busticket-1edeb.firebasestorage.app',
    iosBundleId: 'com.example.womenss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6E7-sLf2rjuLAeDGDAvue3QJkZYJN1qA',
    appId: '1:416377232774:ios:dc8b0f1a3b8e0b8843a007',
    messagingSenderId: '416377232774',
    projectId: 'busticket-1edeb',
    databaseURL: 'https://busticket-1edeb-default-rtdb.firebaseio.com',
    storageBucket: 'busticket-1edeb.firebasestorage.app',
    iosBundleId: 'com.example.womenss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIR7ZWVnNKrsZqbXl5dWRv02JBOnShZNE',
    appId: '1:254948261940:web:d5c2526e5e4cbc9d6c8a61',
    messagingSenderId: '254948261940',
    projectId: 'womensafety-58f57',
    authDomain: 'womensafety-58f57.firebaseapp.com',
    databaseURL: 'https://womensafety-58f57-default-rtdb.firebaseio.com',
    storageBucket: 'womensafety-58f57.firebasestorage.app',
    measurementId: 'G-LPLTXV1XZ1',
  );

}